name: daily-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://exchange-rate-scraper.vercel.app/api/scraper/store-rates' \
          --header 'Authorization: Bearer'
